console.log("lol")

addCommand("editor", "<A-h>", "load-current-config")
addCommand("editor", "<A-g>", "sourceCurrentDocument")

addCommand("editor", "<S-SPACE>ff", "log-options")
addCommand("editor", "<ESCAPE>", "escape")
addCommand("editor", "<S-SPACE><*-l>-", "change-font-size", -1)
addCommand("editor", "<S-SPACE><*-l>+", "change-font-size", 1)
addCommand("editor", "<S-SPACE>l1", "set-layout", "horizontal")
addCommand("editor", "<S-SPACE>l2", "set-layout", "vertical")
addCommand("editor", "<S-SPACE>l3", "set-layout", "fibonacci")
addCommand("editor", "<CA-h>", "change-layout-prop", "main-split", -0.05)
addCommand("editor", "<CA-f>", "change-layout-prop", "main-split", 0.05)
addCommand("editor", "<CA-v>", "create-view")
addCommand("editor", "<CA-a>", "create-keybind-autocomplete-view")
addCommand("editor", "<CA-x>", "close-current-view")
addCommand("editor", "<CA-n>", "prev-view")
addCommand("editor", "<CA-t>", "next-view")
addCommand("editor", "<CS-n>", "move-current-view-prev")
addCommand("editor", "<CS-t>", "move-current-view-next")
addCommand("editor", "<CA-r>", "move-current-view-to-top")
addCommand("editor", "<C-s>", "write-file")
addCommand("editor", "<CS-r>", "load-file")
addCommand("editor", "<S-SPACE><S-SPACE>", "command-line")
addCommand("editor", "<S-SPACE>t", "choose-theme")
addCommand("editor", "<S-SPACE>f", "choose-file", "new")

// addCommand("editor", "<S-SPACE>kn", () => loadNormalBindings())
// addCommand("editor", "<S-SPACE>kv", () => loadVimBindings())
// addCommand("editor", "<S-SPACE>kh", () => loadHelixBindings())

addCommand("commandLine", "<ESCAPE>", "exit-command-line")
addCommand("commandLine", "<ENTER>", "execute-command-line")

addTextCommand("", "<LEFT>", "move-cursor-column -1")
addTextCommand("", "<RIGHT>", "move-cursor-column 1")
addTextCommand("", "<C-d>", "delete-move \"line-next\"")
addTextCommand("", "<C-LEFT>", "move-last \"word-line-back\"")
addTextCommand("", "<C-RIGHT>", "move-last \"word-line\"")
addTextCommand("", "<HOME>", "move-first \"line\"")
addTextCommand("", "<END>", "move-last \"line\"")
addTextCommand("", "<C-UP>", "scroll-text 20")
addTextCommand("", "<C-DOWN>", "scroll-text -20")
addTextCommand("", "<CS-LEFT>", "move-last \"word-line-back\" \"last\"")
addTextCommand("", "<CS-RIGHT>", "move-last \"word-line\" \"last\"")
addTextCommand("", "<UP>", "move-cursor-line -1")
addTextCommand("", "<DOWN>", "move-cursor-line 1")
addTextCommand("", "<C-HOME>", "move-first \"file\"")
addTextCommand("", "<C-END>", "move-last \"file\"")
addTextCommand("", "<CS-HOME>", "move-first \"file\" \"last\"")
addTextCommand("", "<CS-END>", "move-last \"file\" \"last\"")
addTextCommand("", "<S-LEFT>", "move-cursor-column -1 \"last\"")
addTextCommand("", "<S-RIGHT>", "move-cursor-column 1 \"last\"")
addTextCommand("", "<S-UP>", "move-cursor-line -1 \"last\"")
addTextCommand("", "<S-DOWN>", "move-cursor-line 1 \"last\"")
addTextCommand("", "<S-HOME>", "move-first \"line\" \"last\"")
addTextCommand("", "<S-END>", "move-last \"line\" \"last\"")
addTextCommand("", "<CA-d>", "duplicate-last-selection")
addTextCommand("", "<CA-d>", "duplicate-last-selection")
addTextCommand("", "<CA-UP>", "add-cursor-above")
addTextCommand("", "<CA-DOWN>", "add-cursor-below")
addTextCommand("", "<BACKSPACE>", "delete-left")
addTextCommand("", "<DELETE>", "delete-right")
addTextCommand("", "<ENTER>", "insert-text \"\n\"")
addTextCommand("", "<SPACE>", "insert-text \" \"")
addTextCommand("", "<C-l>", "select-line-current")
addTextCommand("", "<A-UP>", "select-parent-current-ts")
addTextCommand("", "<C-r>", "select-prev")
addTextCommand("", "<C-t>", "select-next")
addTextCommand("", "<C-n>", "invert-selection")
addTextCommand("", "<C-y>", "undo")
addTextCommand("", "<C-z>", "redo")